-- MySQL Script generated by MySQL Workbench
-- Mon Sep 24 08:55:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
SET SQL_MODE='ALLOW_INVALID_DATES';
-- -----------------------------------------------------
-- Schema eventos_fccr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventos_fccr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventos_fccr` DEFAULT CHARACTER SET utf8 ;
USE `eventos_fccr` ;

-- -----------------------------------------------------
-- Table `eventos_fccr`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_fccr`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `admin` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_fccr`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_fccr`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `inicio` TIMESTAMP NOT NULL,
  `fim` TIMESTAMP NOT NULL,
  `criador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_usuario_idx` (`criador` ASC),
  CONSTRAINT `fk_eventos_usuario`
    FOREIGN KEY (`criador`)
    REFERENCES `eventos_fccr`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_fccr`.`participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_fccr`.`participantes` (
  `eventos_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`eventos_id`, `usuario_id`),
  INDEX `fk_eventos_has_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_eventos_has_usuario_eventos1_idx` (`eventos_id` ASC),
  CONSTRAINT `fk_eventos_has_usuario_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `eventos_fccr`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `eventos_fccr`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_fccr`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_fccr`.`fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `conteudo` LONGBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_fccr`.`fotos_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_fccr`.`fotos_evento` (
  `fotos_id` INT NOT NULL,
  `eventos_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`fotos_id`, `eventos_id`),
  INDEX `fk_fotos_has_eventos_eventos1_idx` (`eventos_id` ASC),
  INDEX `fk_fotos_has_eventos_fotos1_idx` (`fotos_id` ASC),
  INDEX `fk_fotos_evento_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_fotos_has_eventos_fotos1`
    FOREIGN KEY (`fotos_id`)
    REFERENCES `eventos_fccr`.`fotos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fotos_has_eventos_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `eventos_fccr`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fotos_evento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `eventos_fccr`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_fccr`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_fccr`.`comentario` (
  `eventos_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `comentario` LONGTEXT NULL,
  PRIMARY KEY (`eventos_id`, `usuario_id`),
  INDEX `fk_eventos_has_usuario_usuario2_idx` (`usuario_id` ASC),
  INDEX `fk_eventos_has_usuario_eventos2_idx` (`eventos_id` ASC),
  CONSTRAINT `fk_eventos_has_usuario_eventos2`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `eventos_fccr`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_usuario_usuario2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `eventos_fccr`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
